// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxnfuryijtgijhdhytok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bmZ1cnlpanRnaWpoZGh5dG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjY4MDcsImV4cCI6MjA2NTIwMjgwN30.W0NW6FQeFaXv5_aU0VeAwAjBLW4vxd8u052vuDaHNzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);